apiVersion: v1
kind: Namespace
metadata:
  name: insurance-claims
  labels:
    name: insurance-claims
    environment: production
    app.kubernetes.io/name: insurance-claims
    app.kubernetes.io/part-of: insurance-claim-agent
  annotations:
    description: "Namespace for Insurance Claim Agent microservices"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: insurance-claims-quota
  namespace: insurance-claims
spec:
  hard:
    requests.cpu: "20"
    requests.memory: "40Gi"
    limits.cpu: "40"
    limits.memory: "80Gi"
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: insurance-claims-limits
  namespace: insurance-claims
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      storage: "10Gi"
    type: PersistentVolumeClaim